name: vakpo_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  dio: ^5.5.0+1
  badges: ^3.1.1
  json_annotation: ^4.9.0
  get_it: ^8.0.2
  equatable: ^2.0.5
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.5.1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.7.0
  location: ^7.0.1
  flutter_polyline_points: ^2.1.0
  lottie: ^3.1.2
  pretty_dio_logger: ^1.4.0
  dots_indicator: ^3.0.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  intl: ^0.19.0
  readmore: ^3.0.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/fonts/
  - assets/images/
  - assets/lotties/
